[package]
name = "api"
version = "0.1.1"
edition = "2021"

[dependencies]
axum = { workspace = true }
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
tower = "0.5.2"
tracing = { workspace = true }
telemetry = { path = "../telemetry" }

